---
all:
  children:
    lab:
      hosts:
        elastic-1:
          ansible_host: 10.10.99.11
        kibana-logstash:
          ansible_host: 10.10.99.14
        dns-proxy:
          ansible_host: 10.10.99.12
      vars:
        ansible_user: alpha
        # Le segment est isolé : on passe par le bastion (machine de rebond)
        ansible_ssh_common_args: '-o ProxyJump=alpha@IP_DE_TON_BASTION'
    bastion:
      hosts:
        bastion-vm:
          ansible_host: IP_DE_TON_BASTION
          ansible_user: alpha
